import { readFileSync } from 'node:fs';
import { randomInt } from 'node:crypto';

/**
 * What a Diamond / Black Diamond box can pay out - the SERVER's copy of the game's design pools,
 * so the server rolls the design and a client can never name one.
 *
 * `data/designs.json` is GENERATED by Unity (`EditorTools.DesignManifest.Export`) from
 * `DesignDrops.Pool` itself, never hand-edited - so the pools here are the game's pools. Re-export
 * whenever a design is added, then deploy.
 *
 * A Black Diamond WEAPON carries its RELIC (`relic`): the pair is one payout, minted together.
 */
export interface DesignPiece {
  id: string;
  name: string;
  slot: string;
  class?: string;
  /** Black Diamond relics: the locked finisher. */
  signature?: string;
}

export interface DesignEntry extends DesignPiece {
  relic?: DesignPiece;
}

interface Manifest {
  version: number;
  exportedAt: string;
  costs: { random: number; targeted: number };
  tiers: Record<string, DesignEntry[]>;
}

let manifest: Manifest | null = null;

export function designs(): Manifest {
  manifest ??= JSON.parse(
    readFileSync(new URL('../data/designs.json', import.meta.url), 'utf8'),
  ) as Manifest;
  return manifest;
}

/** DesignDrops.Pool: the tier's designs, optionally narrowed to a slot and (weapons) a class. */
export function pool(tier: string, slot?: string, weaponClass?: string): DesignEntry[] {
  return (designs().tiers[tier] ?? []).filter(
    (d) => (!slot || d.slot === slot) && (!weaponClass || d.slot !== 'Weapon' || d.class === weaponClass),
  );
}

/** A uniform pick from the server's own randomness. */
export function pick(entries: DesignEntry[]): DesignEntry | null {
  return entries.length === 0 ? null : entries[randomInt(entries.length)];
}
